import image1 from "../assets/1.jpg"
import image2 from "../assets/2.webp"
import image3 from "../assets/7.png"
import image4 from "../assets/11.png"
import image5 from "../assets/10.png"
import image6 from "../assets/3.png"
import image7 from "../assets/4.webp"
import image8 from "../assets/5.webp"
import image9 from "../assets/8.png"
export const images=[image1,image2,image3,image4,image5,image6,image7,image8,image9];